# THIS IS MY SAMPLE CONFIG, YOU NEED TO MODIFY TO YOURS

keywords: Aflasio,Gallery,Artwork,Portfolio

menu:
  About: /about #you need to create "about" page first
  Friends: /friends

# Default post title
default_post_title: Untitled #default post title will automatically show if you forgot to write the title of your post

# Default post cover index page
default_cover_index: "/img/seira.jpg" #default cover index will automatically show if you forgot to set up the cover index on your post. This is using square ratio, change to your picture path

favicon: /img/favicon.png #favicon is for your logo on the tab's browser. use transparent BG, more small more good.
logo: img/logo2.svg #logo show in the menu bar
cover_page: img/cover.jpg #cover image will show on the header
profile_pic: /img/450x450/seira.jpg #profil pic will show on the header and left side of the post's title
author: Sira Argia #author's name in post

comments:
  #disqus_shortname: aflasio
  # Facebook comments
  #facebook:
    #appid: 558386947954045
    #comment_count: 5
    #comment_colorscheme: light
  valine:
    appid:  6jbQfaaH3EJezmsqw43NCcNa-gzGzoHsz #your valine appid here get it on https://valine.js.org
    appkey:  5AsBAiusJURpbNDHTP4LHwA6 #your valine appkey here
    notify: false # true/false:mail notify !!!Test,Caution. https://github.com/xCss/Valine/wiki/Valine-%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F%E4%B8%AD%E7%9A%84%E9%82%AE%E4%BB%B6%E6%8F%90%E9%86%92%E8%AE%BE%E7%BD%AE
    verify: false # true/false:verify code
    avatar: mm # avatar style https://github.com/xCss/Valine/wiki/avatar-setting-for-valine
    placeholder: Leave comment # comment box placeholder
    
google_analytics: UA-128493937-1 #get your google analytic on https://analytics.google.com/analytics

# if u want add more profile media social (icon same as Fontawesome 5)
#  just add name ex : Instagram: https://www.instagram.com/you/
social:
  Gitlab: https://gitlab.com/sira313
  Twitter: https://twitter.com/aflasio
  Facebook: https://facebook.com/aflasio.art
  #Google-plus: https://plus.google.com/104751165505597913805
  email: mailto:sira.argia@gmail.com
  #Instagram: https://www.instagram.com/you/
  Telegram: https://t.me/aflasio

# Code Highlight theme
# Available value:
#    default | normal | night | night eighties | night blue | night bright
# https://github.com/chriskempson/tomorrow-theme
highlight_theme: night eighties
